name: 'Prepare Windows'
description: 'Prepare Windows'
inputs:
  java:
    description: 'Package depends on rJava'
    required: false
  jags:
    description: 'Package depends on JAGS'
    required: false

runs:
  using: "composite"
  steps:
    - name: Install rtools
      run: |
        if [ "$RTOOLS43_HOME" ]; then
          echo "Found preinstalled toolchain in $RTOOLS43_HOME"
          echo "RTOOLS42_HOME=$RTOOLS43_HOME" >> $GITHUB_ENV
          echo "RTOOLS44_HOME=$RTOOLS43_HOME" >> $GITHUB_ENV
        elif [ "$RTOOLS44_HOME" ]; then
          echo "Found preinstalled toolchain in $RTOOLS44_HOME"
          echo "RTOOLS42_HOME=$RTOOLS44_HOME" >> $GITHUB_ENV
          echo "RTOOLS43_HOME=$RTOOLS44_HOME" >> $GITHUB_ENV
        else
          echo "No rtools installation found!"
        fi
        echo "_R_INSTALL_TIME_PATCHES_=https://www.r-project.org/nosvn/winutf8/ucrt3/" >> $GITHUB_ENV
      shell: bash

    - name: "Install JAGS if needed"
      run: |
        curl -o JAGS.exe -L https://github.com/r-windows/files/releases/download/JAGS/JAGS-4.3.1.exe
        Start-Process "JAGS.exe" -argumentlist "/S" -wait
        Remove-Item JAGS.exe
      shell: pwsh
      if: inputs.jags

    - name: "Install Pandoc"
      run: choco install -y --no-progress pandoc
      shell: pwsh
      continue-on-error: true
