name: 'R CMD check'
description: 'Prepare and check a package'
inputs:
  sourcepkg:
    description: 'File of the source package'
    required: true
  checkargs:
    description: 'Extra args for R CMD check'
    default: --no-manual --no-build-vignettes
    required: true
  cranlikerepo:
    description: 'URL of the package repository with dependencies'
    default: 'Sys.getenv("MY_UNIVERSE", "https://dev.ropensci.org")'
    required: true
  java:
    description: 'Package depends on rJava'
    required: false
  jags:
    description: 'Package depends on JAGS'
    required: false

outputs:
  binarypkg:
    description: 'Filename of the output binary package'
    value: ${{steps.results.outputs.binarypkg}}
  hasplatform:
    description: 'The build is only for one architecture'
    value: ${{steps.results.outputs.hasplatform}}

runs:
  using: "composite"
  steps:
    - name: "Setup R package library"
      shell: bash
      run: |
        sed -i.bak 's/-mmacosx-version-min=10.13//g' $(R RHOME)/etc/Makeconf
        sed -i.bak 's|darwin18/8.2.0|darwin20.0/12.2.0|g' $(R RHOME)/etc/Makeconf
        echo "::group::Setup R package library"
        if [ "${R_LIBS_USER}" ]; then mkdir -p $R_LIBS_USER; fi
        echo 'if(grepl("4.3", getRversion())) options(repos = c(CRAN = "https://cloud.r-project.org"))' > $R_PROFILE_USER
        echo 'if(grepl("4.2", getRversion())) options(repos = c(CRAN = "https://p3m.dev/cran/latest"))' >> $R_PROFILE_USER
        echo 'options(Ncpus = 2, crayon.enabled = TRUE)' >> $R_PROFILE_USER
        echo 'if(grepl("4.2", getRversion())) Sys.setenv(R_BIOC_VERSION=3.16)' >> $R_PROFILE_USER
        echo 'if(grepl("4.3", getRversion())) Sys.setenv(R_BIOC_VERSION=3.18)' >> $R_PROFILE_USER
        # echo 'if(grepl("4.3", getRversion())) options(BioC_mirror = "https://bioc.cran.dev")' >> $R_PROFILE_USER
        echo 'utils::setRepositories(ind = 1:3)' >> $R_PROFILE_USER
        echo 'Sys.unsetenv(c("CI", "GITHUB_ACTIONS"))' >> $R_PROFILE_USER
        echo 'options(HTTPUserAgent = paste0(getOption("HTTPUserAgent"), "; r-universe"))' >> $R_PROFILE_USER
        echo 'options(repos = c(universe = trimws(strsplit(${{inputs.cranlikerepo}}, ";")[[1]]), getOption("repos")))' >> $R_PROFILE_USER
        cat $R_PROFILE_USER
        echo "JAVA_HOME=$JAVA_HOME_11_X64" >> $GITHUB_ENV
        R --version | grep darwin20 && echo "MACOSX_DEPLOYMENT_TARGET=11.0" >> $GITHUB_ENV
        #if test -d /Library/Frameworks/R.framework/Versions/4.3-x86_64; then
        #  sudo mv /Library/Frameworks/R.framework/Versions/4.2 /Library/Frameworks/R.framework/Versions/4.2old || true
        #  sudo ln -sf /Library/Frameworks/R.framework/Versions/4.3-x86_64 /Library/Frameworks/R.framework/Versions/4.2
        #fi
        R CMD javareconf || true
        echo "::endgroup::"
      env:
        R_PROFILE_USER: .Rprofile

    - name: "Start fake X11 server"
      shell: bash
      continue-on-error: true
      run: |
        nohup /opt/X11/bin/Xvfb :6 -screen 0 1280x1024x24 > ~/X.log 2>&1 &
        export DISPLAY=:6
        echo "Running fake X server on $DISPLAY"
        echo "DISPLAY=$DISPLAY" >> $GITHUB_ENV

    - name: Install package dependencies
      run: |
        cat('::group::Install package dependencies\n')
        install.packages('remotes')
        pkg_deps <- remotes::local_package_deps("${{inputs.sourcepkg}}", dependencies = TRUE)
        installed <- row.names(installed.packages())
        update.packages(oldPkgs = pkg_deps, ask = FALSE)
        needpkg <- setdiff(pkg_deps, installed)
        avail <- row.names(available.packages())
        install <- intersect(needpkg, avail)
        unavail <- setdiff(needpkg, avail)
        install.packages(install)
        if(length(unavail)) {
          warning("Installing from remotes: ", paste(unavail, collapse = ','))
          remotes::install_deps("${{inputs.sourcepkg}}", dependencies = TRUE, upgrade = FALSE)
        }
        cat('::endgroup::\n')
      shell: Rscript {0}
      env:
        R_DEFAULT_INTERNET_TIMEOUT: 150
#        PKG_CONFIG_PATH: /usr/local/lib/pkgconfig:/opt/X11/lib/pkgconfig
#        PROJ_LIB: /usr/local/share/proj
        PROJ_GDAL_DATA_COPY: TRUE
        R_PROFILE_USER: .Rprofile
#        R_COMPILE_AND_INSTALL_PACKAGES: never
    - name: Build and check package
      shell: bash
      run: R CMD check ${{inputs.sourcepkg}} --install-args="--build" ${{inputs.checkargs}}
      env:
#       MACOSX_DEPLOYMENT_TARGET: 11.0
        #NB: Remove SDKROOT below when using building on newer macOS
        SDKROOT: /Library/Developer/CommandLineTools/SDKs/MacOSX11.sdk
        R_BROWSER: echo
        R_PDFVIEWER: echo
        RGL_USE_NULL: TRUE
        R_TEXI2DVICMD: emulation
        NOT_CRAN: FALSE
#        PKG_CONFIG_PATH: /usr/local/lib/pkgconfig:/opt/X11/lib/pkgconfig
#        PROJ_LIB: /usr/local/share/proj
        PROJ_GDAL_DATA_COPY: TRUE
        ARROW_R_DEV: TRUE
        R_PROFILE_USER: .Rprofile
        _R_CHECK_FORCE_SUGGESTS_: FALSE
        _R_CHECK_CRAN_INCOMING_: FALSE
        _R_CHECK_CRAN_INCOMING_REMOTE_: FALSE
        _R_SHLIB_STRIP_: TRUE
        _R_CHECK_TIMINGS_: 5

    - name: Inspect check outputs
      if: always()
      id: results
      shell: bash
      run: |
        SOURCEPKG="${{ inputs.sourcepkg }}"
        BINARYPKG="${SOURCEPKG%tar.gz}tgz"
        PKGNAME=$(echo $SOURCEPKG | cut -d '_' -f1)
        if [ -f "${BINARYPKG}" ]; then
          echo "Built binary package: $BINARYPKG"
          echo "binarypkg=$BINARYPKG" >> $GITHUB_OUTPUT
          if tar -xOf "${BINARYPKG}" "${PKGNAME}/DESCRIPTION" | grep -q '^Built.*x86_64'; then
            echo "hasplatform=true" >> $GITHUB_OUTPUT
          fi
        else
          echo "No binary package $BINARYPKG found. Skipping deployment."
        fi
        find . -regex '.*\.R*out' | while read f; do echo "::group::$f"; echo " ===== $f ====="; tail -n1000 $f; echo "::endgroup::"; done
        find . -regex '.*\.fail' | while read f; do echo "::group::$f"; echo " ===== $f ====="; tail -n1000 $f; echo "::endgroup::"; done
